<?php
/** 
 * SGU Space Blocks Class
 * 
 * Handles Gutenberg block registration and rendering for astronomy-related blocks.
 * Provides block editor integration with real-time previews and delegates rendering
 * to existing shortcode infrastructure on the front-end.
 * 
 * @since 0.0.1
 * @author Kevin Pirnie <me@kpirnie.com>
 * @package US Star Gazers Plugin
 * 
*/

// We don't want to allow direct access to this
defined( 'ABSPATH' ) || die( 'No direct script access allowed' );

// Make sure this class doesn't already exist
if ( ! class_exists( 'SGU_Space_Blocks' ) ) {

    /** 
     * Class SGU_Space_Blocks
     * 
     * Registers and manages Gutenberg blocks for displaying astronomy data.
     * Each block wraps existing shortcode functionality to maintain consistency
     * between block-based and shortcode-based implementations.
     * 
     * Available blocks:
     * - sgup/latest-alerts: Display latest astronomy alerts with customizable title
     * - sgup/cme-alerts: Coronal Mass Ejection alerts with pagination
     * - sgup/flare-alerts: Solar flare alerts with pagination
     * - sgup/sw-alerts: Space weather alerts with pagination
     * - sgup/geomag-alerts: Geomagnetic storm alerts with pagination
     * - sgup/astro-menu: Navigation menu for astronomy sections
     * - sgup/neos: Near Earth Objects data with optional map display
     * - sgup/apod: Astronomy Picture of the Day
     * 
     * @since 0.0.1
     * @access public
     * @author Kevin Pirnie <me@kpirnie.com>
     * @package US Star Gazers Plugin
     * 
    */
    final class SGU_Space_Blocks {

        /** @var string Block category slug for space blocks */
        private const CATEGORY = 'sgup_space';

        /** @var int Default Block API version */
        private const API_VERSION = 3;

        /** @var array Block supports configuration */
        private readonly array $supports;

        /** @var SGU_Space_Data_Get Space data handler */
        private readonly SGU_Space_Data_Get $space_data;

        /** @var int Current page number for pagination */
        private readonly int $paged;

        /** 
         * __construct
         * 
         * Initialize the class and setup dependencies
         * 
         * @since 0.0.1
         * @access public
         * @author Kevin Pirnie <me@kpirnie.com>
         * @package US Star Gazers Plugin
         * 
        */
        public function __construct() {

            // instantiate space data handler
            $this->space_data = new SGU_Space_Data_Get();

            // get the current page number
            $this->paged = SGU_Static::safe_get_paged_var() ?: 1;

            // hold the supports array
            $this->supports = [
                'align' => true,
                'className' => true,
                'customClassName' => true,
                'spacing' => [
                    'margin' => true,
                    'padding' => true,
                    'blockGap' => true,
                ],
            ];

        }

        /** 
         * init
         * 
         * Initialize the blocks system by registering WordPress hooks.
         * This method sets up both the block registration and editor asset enqueuing.
         * Must be called early in the WordPress init sequence (priority < 10).
         * 
         * @since 0.0.1
         * @access public
         * @author Kevin Pirnie <me@kpirnie.com>
         * @package US Star Gazers Plugin
         * 
         * @return void This method does not return anything
         * 
        */
        public function init(): void {

            // Register all blocks during WordPress initialization
            // This must happen before WordPress processes blocks on pages
            add_action( 'init', $this->register_blocks( ... ) );
            
            // Enqueue JavaScript for block editor previews and controls
            // Only loads in wp-admin block editor, not on front-end
            add_action( 'enqueue_block_editor_assets', $this->enqueue_editor_assets( ... ) );

            // Hook into the filter
            add_filter( 'block_categories_all', $this->register_block_categories( ... ), 5, 2 );

        }

        /** 
         * enqueue_editor_assets
         * 
         * Enqueue JavaScript and dependencies for the block editor.
         * Loads the compiled blocks.js file with all block registrations,
         * edit functions, and save functions for the Gutenberg editor.
         * 
         * The asset file (blocks.asset.php) is generated by webpack and contains
         * the correct dependencies and version hash for cache busting.
         * 
         * @since 0.0.1
         * @access public
         * @author Kevin Pirnie <me@kpirnie.com>
         * @package US Star Gazers Plugin
         * 
         * @return void This method does not return anything
         * 
        */
        public function enqueue_editor_assets(): void {
    
            // Get the correct plugin directory URL
            $plugin_url = plugins_url( '/', SGUP_PATH . '/' . SGUP_FILENAME );
            
            // Build path to the webpack-generated asset file
            $asset_file = SGUP_PATH . '/build/blocks.asset.php';
            
            // Load asset file if it exists, otherwise use defaults
            $asset = file_exists( $asset_file ) ? require $asset_file : [
                'dependencies' => [ 'wp-blocks', 'wp-element', 'wp-block-editor', 'wp-components', 'wp-i18n' ],
                'version' => '1.0.0',
            ];

            // Enqueue the compiled blocks JavaScript for the editor
            wp_enqueue_script(
                'sgup-blocks-editor',
                $plugin_url . 'build/blocks.js',
                $asset['dependencies'],
                $asset['version'],
                true
            );

        }

        /** 
         * register_block
         * 
         * Register a single Gutenberg block with common configuration
         * 
         * @since 0.0.1
         * @access private
         * @author Kevin Pirnie <me@kpirnie.com>
         * @package US Star Gazers Plugin
         * 
         * @param string $name Block name (e.g., 'sgup/latest-alerts')
         * @param array $attributes Block attributes definition
         * @param callable $render_callback Render callback function
         * 
         * @return void
         * 
        */
        private function register_block( string $name, array $attributes, callable $render_callback ): void {

            register_block_type( $name, [
                'api_version' => self::API_VERSION,
                'category' => self::CATEGORY,
                'render_callback' => $render_callback,
                'attributes' => $attributes,
                'supports' => $this->supports,
            ] );

        }

        /** 
         * paging_attributes
         * 
         * Get paging attributes common to paginated blocks
         * 
         * @since 0.0.1
         * @access private
         * @author Kevin Pirnie <me@kpirnie.com>
         * @package US Star Gazers Plugin
         * 
         * @return array Paging attributes array
         * 
        */
        private function paging_attributes(): array {

            return [
                'showPaging' => [ 'type' => 'boolean', 'default' => false ],
                'pagingLocation' => [ 'type' => 'string', 'default' => 'bottom', 'enum' => [ 'top', 'bottom', 'both' ] ],
                'perPage' => [ 'type' => 'number', 'default' => 6 ],
            ];

        }

        /** 
         * paging_data
         * 
         * Build paging data array common to paginated block templates
         * 
         * @since 0.0.1
         * @access private
         * @author Kevin Pirnie <me@kpirnie.com>
         * @package US Star Gazers Plugin
         * 
         * @param array $attributes Block attributes
         * @param object|null $query_data Query data object with max_num_pages
         * 
         * @return array Paging data array for template
         * 
        */
        private function paging_data( array $attributes, ?object $query_data = null ): array {

            return [
                'show_paging' => filter_var( $attributes['showPaging'] ?? false, FILTER_VALIDATE_BOOLEAN ),
                'paging_location' => sanitize_text_field( $attributes['pagingLocation'] ?? 'bottom' ),
                'per_page' => absint( $attributes['perPage'] ?? 6 ) ?: 6,
                'max_pages' => $query_data?->max_num_pages ?? 1,
                'paged' => $this->paged,
            ];

        }

        /** 
         * register_blocks
         * 
         * Register all Gutenberg blocks with WordPress.
         * Each block is registered with a render callback that delegates to existing
         * shortcode infrastructure, maintaining consistency between blocks and shortcodes.
         * 
         * Blocks are server-side rendered, meaning the render_callback generates
         * the HTML output on both front-end and in the editor preview.
         * 
         * @since 0.0.1
         * @access public
         * @author Kevin Pirnie <me@kpirnie.com>
         * @package US Star Gazers Plugin
         * 
         * @return void This method does not return anything
         * 
        */
        public function register_blocks(): void {

            // Register Latest Alerts block
            // Displays the most recent astronomy alerts with a customizable title
            $this->register_block(
                'sgup/latest-alerts',
                [
                    'title' => [ 'type' => 'string', 'default' => 'Latest Astronomy Alerts' ],
                ],
                function( array $attributes ): string {

                    // pull the latest alert data
                    $latest_alerts = $this->space_data->get_latest_alerts();

                    // hold the data we're going to pass to the template
                    $data = [
                        'title' => esc_html( $attributes['title'] ?? 'Latest Astronomy Alerts' ),
                        'latest_alerts' => $latest_alerts,
                    ];

                    // render the template
                    return SGU_Static::render_template( 'astro/alerts/latest', $data );

                }
            );

            // Register CME (Coronal Mass Ejection) Alerts block
            // Displays CME alerts with optional pagination controls
            $this->register_block(
                'sgup/cme-alerts',
                $this->paging_attributes(),
                function( array $attributes ): string {

                    // get the CME alert data
                    $alerts = $this->space_data->get_cme_alerts( $this->paged );

                    // make sure there is data, if not dump out early
                    if ( ! $alerts || ! $alerts->posts ) {
                        return '';
                    }

                    // hold the data we're going to pass to the template
                    $data = $this->paging_data( $attributes, $alerts ) + [
                        'data' => $alerts,
                    ];

                    // render the template
                    return SGU_Static::render_template( 'astro/alerts/cme', $data );

                }
            );

            // Register Solar Flare Alerts block
            // Displays solar flare event data with optional pagination
            $this->register_block(
                'sgup/flare-alerts',
                $this->paging_attributes(),
                function( array $attributes ): string {

                    // get the solar flare alert data
                    $alerts = $this->space_data->get_solar_flare_alerts( $this->paged );

                    // make sure there is data, if not dump out early
                    if ( ! $alerts || ! $alerts->posts ) {
                        return '';
                    }

                    // hold the data we're going to pass to the template
                    $data = $this->paging_data( $attributes, $alerts ) + [
                        'data' => $alerts,
                    ];

                    // render the template
                    return SGU_Static::render_template( 'astro/alerts/solar-flare', $data );

                }
            );

            // Register Space Weather Alerts block
            // Displays general space weather notifications with pagination
            $this->register_block(
                'sgup/sw-alerts',
                $this->paging_attributes(),
                function( array $attributes ): string {

                    // get the space weather alert data
                    $alerts = $this->space_data->get_space_weather_alerts( $this->paged );

                    // make sure there is data, if not dump out early
                    if ( ! $alerts || ! $alerts->posts ) {
                        return '';
                    }

                    // hold the data we're going to pass to the template
                    $data = $this->paging_data( $attributes, $alerts ) + [
                        'data' => $alerts,
                    ];

                    // render the template
                    return SGU_Static::render_template( 'astro/alerts/space-weather', $data );

                }
            );

            // Register Geomagnetic Storm Alerts block
            // Displays geomagnetic activity alerts with pagination options
            $this->register_block(
                'sgup/geomag-alerts',
                $this->paging_attributes(),
                function( array $attributes ): string {

                    // get the geomagnetic alert data
                    $alerts = $this->space_data->get_geo_magnetic_alerts( $this->paged );

                    // make sure there is data, if not dump out early
                    if ( ! $alerts || ! $alerts->posts ) {
                        return '';
                    }

                    // hold the data we're going to pass to the template
                    $data = $this->paging_data( $attributes, $alerts ) + [
                        'data' => $alerts,
                    ];

                    // render the template
                    return SGU_Static::render_template( 'astro/alerts/geomagnetic', $data );

                }
            );

            // Register Astronomy Menu block
            // Displays navigation menu for astronomy sections
            // 'which' attribute determines which menu variation to show
            $this->register_block(
                'sgup/astro-menu',
                [
                    'which' => [ 'type' => 'string', 'default' => 'alert-menu' ],
                    'text_align' => [ 'type' => 'string', 'default' => 'left' ],
                    'is_inline' => [ 'type' => 'boolean', 'default' => false ],
                ],
                function( array $attributes ): string {

                    // sanitize the attributes
                    $menu_slug = sanitize_text_field( $attributes['which'] ?? 'alert-menu' );
                    $text_align = sanitize_text_field( $attributes['text_align'] ?? 'left' );
                    $is_inline = filter_var( $attributes['is_inline'] ?? false, FILTER_VALIDATE_BOOLEAN );

                    // Create cache key for this specific menu
                    $cache_key = "sgup_astro_menu_{$menu_slug}";

                    // Try to get cached menu
                    $cached = wp_cache_get( $cache_key, 'sgup_menus' );
                    if ( $cached !== false ) {
                        return $cached;
                    }

                    // configure the menu from our themes menus
                    $alert_nav_conf = [
                        'menu' => $menu_slug,
                        'items_wrap' => '%3$s',
                        'depth' => 1,
                        'container' => null,
                        'echo' => false,
                        'menu_class' => '',
                    ];

                    // get the menu
                    $the_menu = wp_nav_menu( $alert_nav_conf );

                    // hold the data we're going to pass to the template
                    $data = [
                        'the_menu' => $the_menu,
                        'is_inline' => $is_inline,
                        'text_align' => $text_align,
                    ];

                    // render the template
                    $output = SGU_Static::render_template( 'astro/menu', $data );

                    // Cache for 12 hours (menus don't change often)
                    wp_cache_set( $cache_key, $output, 'sgup_menus', 12 * HOUR_IN_SECONDS );

                    // return the output
                    return $output;

                }
            );

            // Register Near Earth Objects (NEO) block
            // Displays NEO tracking data with optional map visualization and pagination
            $this->register_block(
                'sgup/neos',
                $this->paging_attributes() + [
                    'showMap' => [ 'type' => 'boolean', 'default' => false ],
                ],
                function( array $attributes ): string {

                    // get the NEO data
                    $neos = $this->space_data->get_neos( $this->paged );

                    // hold the data we're going to pass to the template
                    $data = $this->paging_data( $attributes, $neos ) + [
                        'show_map' => filter_var( $attributes['showMap'] ?? false, FILTER_VALIDATE_BOOLEAN ),
                        'data' => $neos,
                    ];

                    // render the template
                    return SGU_Static::render_template( 'astro/neos', $data );

                }
            );

            // Register Astronomy Picture of the Day (APOD) block
            // Displays NASA's APOD with image and description
            $this->register_block(
                'sgup/apod',
                [
                    'title' => [ 'type' => 'string', 'default' => 'Astronomy Picture of the Day' ],
                ],
                function( array $attributes ): string {

                    // get the APOD data
                    $apod = $this->space_data->get_apod();

                    // Early return if no data
                    if ( ! $apod || empty( $apod->posts ) ) {
                        return '';
                    }

                    // setup the post
                    $post = $apod->posts[0];

                    // hold the data we're going to pass to the template
                    $data = [
                        'id' => $post->ID,
                        'block_title' => esc_html( $attributes['title'] ?? 'Astronomy Picture of the Day' ),
                        'title' => $post->post_title,
                        'content' => $post->post_content,
                        'meta' => get_post_meta( $post->ID ),
                    ];

                    // render the template
                    return SGU_Static::render_template( 'astro/apod/home', $data );

                }
            );

            // Register Light Pollution Map block
            $this->register_block(
                'sgup/light-pollution',
                [
                    'title' => [ 'type' => 'string', 'default' => 'Light Pollution Map' ],
                    'showTitle' => [ 'type' => 'boolean', 'default' => true ],
                    'showLocationPicker' => [ 'type' => 'boolean', 'default' => true ],
                    'maxHeight' => [ 'type' => 'number', 'default' => 450 ],
                ],
                function( array $attributes ): string {

                    // get the location data
                    $location_handler = new SGU_Weather_Location();
                    $location = $location_handler->get_stored_location();
                    $location_name = $location?->name ?? '';

                    // hold the data we're going to pass to the template
                    $data = [
                        'title' => $attributes['title'] ?? 'Light Pollution Map',
                        'show_title' => $attributes['showTitle'] ?? true,
                        'show_location_picker' => $attributes['showLocationPicker'] ?? true,
                        'max_height' => $attributes['maxHeight'] ?? 450,
                        'has_location' => (bool) $location,
                        'location' => $location,
                        'location_name' => $location_name,
                        'latitude' => $location?->lat ?? 19.8987,
                        'longitude' => $location?->lon ?? -155.6659,
                        'wrapper_attr' => get_block_wrapper_attributes(),
                    ];

                    // render the template
                    return SGU_Static::render_template( 'astro/lightpollution-map', $data );

                }
            );

            // Register Sun Rise/Set block
            $this->register_block(
                'sgup/sun-riseset',
                [
                    'title'              => [ 'type' => 'string', 'default' => 'Sun Times' ],
                    'showTitle'          => [ 'type' => 'boolean', 'default' => true ],
                    'showLocationPicker' => [ 'type' => 'boolean', 'default' => true ],
                ],
                function( array $attributes ): string {

                    wp_enqueue_style( 'sgu-sky-tonight' );

                    $location_handler = new SGU_Weather_Location();
                    $location         = $location_handler->get_stored_location();
                    $location_name    = $location?->name ?? '';
                    $latitude         = $location?->lat ?? 19.8987;
                    $longitude        = $location?->lon ?? -155.6659;

                    $usno = new SGU_USNO_API();
                    $rise_set = $usno->get_rise_set_data( $latitude, $longitude );

                    $data = [
                        'title'                => $attributes['title'] ?? 'Sun Times',
                        'show_title'           => $attributes['showTitle'] ?? true,
                        'show_location_picker' => $attributes['showLocationPicker'] ?? true,
                        'wrapper_attr'         => get_block_wrapper_attributes(),
                        'has_location'         => (bool) $location,
                        'location'             => $location,
                        'location_name'        => $location_name,
                        'latitude'             => $latitude,
                        'longitude'            => $longitude,
                        'sun'                  => $rise_set?->sun ?? null,
                    ];

                    return SGU_Static::render_template( 'astro/sun-riseset', $data );
                }
            );

            // Register Moon Rise/Set block
            $this->register_block(
                'sgup/moon-riseset',
                [
                    'title'              => [ 'type' => 'string', 'default' => 'Moon Times' ],
                    'showTitle'          => [ 'type' => 'boolean', 'default' => true ],
                    'showLocationPicker' => [ 'type' => 'boolean', 'default' => true ],
                ],
                function( array $attributes ): string {

                    wp_enqueue_style( 'sgu-sky-tonight' );

                    $location_handler = new SGU_Weather_Location();
                    $location         = $location_handler->get_stored_location();
                    $location_name    = $location?->name ?? '';
                    $latitude         = $location?->lat ?? 19.8987;
                    $longitude        = $location?->lon ?? -155.6659;

                    $usno     = new SGU_USNO_API();
                    $rise_set = $usno->get_rise_set_data( $latitude, $longitude );

                    $data = [
                        'title'                => $attributes['title'] ?? 'Moon Times',
                        'show_title'           => $attributes['showTitle'] ?? true,
                        'show_location_picker' => $attributes['showLocationPicker'] ?? true,
                        'wrapper_attr'         => get_block_wrapper_attributes(),
                        'has_location'         => (bool) $location,
                        'location'             => $location,
                        'location_name'        => $location_name,
                        'latitude'             => $latitude,
                        'longitude'            => $longitude,
                        'moon'                 => $rise_set?->moon ?? null,
                        'moon_phase'           => $rise_set?->moon_phase ?? null,
                    ];

                    return SGU_Static::render_template( 'astro/moon-riseset', $data );
                }
            );

            // Register Planet Positions block
            $this->register_block(
                'sgup/planet-positions',
                [
                    'title'              => [ 'type' => 'string', 'default' => 'Planet Positions' ],
                    'showTitle'          => [ 'type' => 'boolean', 'default' => true ],
                    'showLocationPicker' => [ 'type' => 'boolean', 'default' => true ],
                ],
                function( array $attributes ): string {
                    wp_enqueue_style( 'sgu-sky-tonight' );
                    $location_handler = new SGU_Weather_Location();
                    $location         = $location_handler->get_stored_location();
                    $location_name    = $location?->name ?? '';
                    $latitude         = $location?->lat ?? 19.8987;
                    $longitude        = $location?->lon ?? -155.6659;
                    $astronomy_api = new SGU_Space_API();
                    $planets       = [];
                    if ( $astronomy_api->has_credentials() ) {
                        $positions = $astronomy_api->get_planet_positions( $latitude, $longitude );
                        // FIX: Changed from $positions->data->rows to $positions->data->table->rows
                        if ( $positions && isset( $positions->data->table->rows ) ) {
                            $planet_ids = [ 'mercury', 'venus', 'mars', 'jupiter', 'saturn', 'uranus', 'neptune' ];
                            foreach ( $positions->data->table->rows as $row ) {
                                $body_id = strtolower( $row->entry->id ?? '' );
                                if ( ! in_array( $body_id, $planet_ids, true ) ) {
                                    continue;
                                }
                                // FIX: Changed from $row->positions[0] to $row->cells[0]
                                $cell = $row->cells[0] ?? null;
                                if ( ! $cell ) {
                                    continue;
                                }
                                $altitude = (float) ( $cell->position->horizontal->altitude->degrees ?? -90 );
                                $planets[] = (object) [
                                    'name'          => $row->entry->name,
                                    'id'            => $body_id,
                                    'visible'       => $altitude > 0,
                                    'altitude'      => $altitude,
                                    'azimuth'       => (float) ( $cell->position->horizontal->azimuth->degrees ?? 0 ),
                                    'constellation' => $cell->position->constellation->name ?? '',
                                ];
                            }
                            usort( $planets, fn( $a, $b ) => $b->altitude <=> $a->altitude );
                        }
                    }
                    $data = [
                        'title'                => $attributes['title'] ?? 'Planet Positions',
                        'show_title'           => $attributes['showTitle'] ?? true,
                        'show_location_picker' => $attributes['showLocationPicker'] ?? true,
                        'wrapper_attr'         => get_block_wrapper_attributes(),
                        'has_location'         => (bool) $location,
                        'location'             => $location,
                        'location_name'        => $location_name,
                        'latitude'             => $latitude,
                        'longitude'            => $longitude,
                        'planets'              => $planets,
                        'has_credentials'      => $astronomy_api->has_credentials(),
                    ];

                    // pull the template
                    return SGU_Static::render_template( 'astro/planet-positions', $data );
                }
            );

            // Register Star Chart block
            $this->register_block(
                'sgup/star-chart',
                [
                    'title'                      => [ 'type' => 'string', 'default' => 'Star Chart' ],
                    'showTitle'                  => [ 'type' => 'boolean', 'default' => true ],
                    'showLocationPicker'         => [ 'type' => 'boolean', 'default' => true ],
                    'projection'                 => [ 'type' => 'string', 'default' => 'stereo' ],
                    'style'                      => [ 'type' => 'string', 'default' => 'default' ],
                    'zoom'                       => [ 'type' => 'number', 'default' => 3 ],
                    'az'                         => [ 'type' => 'number', 'default' => 180 ],
                    'showStars'                  => [ 'type' => 'boolean', 'default' => true ],
                    'showStarLabels'             => [ 'type' => 'boolean', 'default' => false ],
                    'showConstellations'         => [ 'type' => 'boolean', 'default' => true ],
                    'showConstellationLabels'    => [ 'type' => 'boolean', 'default' => true ],
                    'showPlanets'                => [ 'type' => 'boolean', 'default' => true ],
                    'showPlanetLabels'           => [ 'type' => 'boolean', 'default' => true ],
                    'showOrbits'                 => [ 'type' => 'boolean', 'default' => false ],
                    'showGalaxy'                 => [ 'type' => 'boolean', 'default' => true ],
                    'ground'                     => [ 'type' => 'boolean', 'default' => true ],
                    'gradient'                   => [ 'type' => 'boolean', 'default' => true ],
                    'keyboard'                   => [ 'type' => 'boolean', 'default' => true ],
                    'mouse'                      => [ 'type' => 'boolean', 'default' => true ],
                    'live'                       => [ 'type' => 'boolean', 'default' => false ],
                ],
                function( array $attributes ): string {
                    wp_enqueue_style( 'sgu-sky-tonight' );
                    $location_handler = new SGU_Weather_Location();
                    $location         = $location_handler->get_stored_location();
                    $location_name    = $location?->name ?? '';
                    $latitude         = $location?->lat ?? 19.8987;
                    $longitude        = $location?->lon ?? -155.6659;
                    $data = [
                        'title'                      => $attributes['title'] ?? 'Star Chart',
                        'show_title'                 => $attributes['showTitle'] ?? true,
                        'show_location_picker'       => $attributes['showLocationPicker'] ?? true,
                        'wrapper_attr'               => get_block_wrapper_attributes(),
                        'has_location'               => (bool) $location,
                        'location'                   => $location,
                        'location_name'              => $location_name,
                        'latitude'                   => $latitude,
                        'longitude'                  => $longitude,
                        'projection'                 => $attributes['projection'] ?? 'stereo',
                        'style'                      => $attributes['style'] ?? 'default',
                        'zoom'                       => $attributes['zoom'] ?? 3,
                        'az'                         => $attributes['az'] ?? 180,
                        'show_stars'                 => $attributes['showStars'] ?? true,
                        'show_star_labels'           => $attributes['showStarLabels'] ?? false,
                        'show_constellations'        => $attributes['showConstellations'] ?? true,
                        'show_constellation_labels'  => $attributes['showConstellationLabels'] ?? true,
                        'show_planets'               => $attributes['showPlanets'] ?? true,
                        'show_planet_labels'         => $attributes['showPlanetLabels'] ?? true,
                        'show_orbits'                => $attributes['showOrbits'] ?? false,
                        'show_galaxy'                => $attributes['showGalaxy'] ?? true,
                        'ground'                     => $attributes['ground'] ?? true,
                        'gradient'                   => $attributes['gradient'] ?? true,
                        'keyboard'                   => $attributes['keyboard'] ?? true,
                        'mouse'                      => $attributes['mouse'] ?? true,
                        'live'                       => $attributes['live'] ?? false,
                    ];
                    return SGU_Static::render_template( 'astro/star-chart', $data );
                }
            );

        }

        /** 
         * register_block_categories
         * 
         * Register custom block categories for space and weather blocks.
         * Categories appear in the block inserter to group related blocks together.
         * 
         * @since 0.0.1
         * @access public
         * @author Kevin Pirnie <me@kpirnie.com>
         * @package US Star Gazers Plugin
         * 
         * @param array $categories Existing block categories
         * @param WP_Block_Editor_Context $context Current context
         * 
         * @return array Modified block categories
         * 
        */
        public function register_block_categories( array $categories, WP_Block_Editor_Context $context ): array {

            // merge our new categories in with the existing ones
            return array_merge(
                [
                    [
                        'slug' => 'sgup_space',
                        'title' => __( 'Space', 'sgup' ),
                    ],
                    [
                        'slug' => 'sgup_weather',
                        'title' => __( 'Weather', 'sgup' ),
                    ],
                ],
                $categories
            );

        }

    }

}
